name: CI - PHPUnit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  phpunit:
    uses: OxfordInformationLabs/ci-workflows/.github/workflows/phpunit.yml@main
    with:
      php-version: "8.2"
      coverage: false
      test-directory: "test"